### PR TITLE
Search in HOME for startup.lg, instead of cwd.

### PR DESCRIPTION
**Pull request by jrincayc**
Search in HOME for startup.lg, instead of cwd.

Also change to looking for startup.lg instead of startup since startup
might find some other program's file.

### CODE REVIEW

**Comment by jrincayc** [comment]
@brianharvey   Looking at the code, startup is looked for in the current working directory, and startup.lg is looked for in the logolib.  I changed startup to look for it in $HOME, should startup.lg be in $HOME as well?  Actually, on second thought, startup might be too generic to be put in home (some other program might look for that as well, so maybe logo should not look for a file startup at all. I could change it to look for startup.lg in $HOME/startup.lg and stop looking for startup.

**Comment by brianharvey** [comment]
It should definitely look in logolib.  As for the one in $HOME, I guess that could change to startup.lg also.  Thanks.

**Comment by jrincayc** [comment]
Now it looks for startup.lg in logolib and in $HOME (If both are found, it will run both)

**Comment by brianharvey** [comment]
Cool.  Let me know when you're ready for a release!  Sounds close.

**Pull request merged**
