### PR TITLE
remove double spaces

### PR DESCRIPTION
**Pull request by n3oney**
Remove the double space in "I don't know how  to %p"

### CODE REVIEW

**Comment by dmalec** [comment]
I believe the double space is by design based on

_Proceedings of the ACM on Programming Languages_ June 2020 Article No.: 79 Page 28
https://doi.org/10.1145/3386329

> A story Paul Goldenberg recounts from the early days of Logo is that one day a child typed the command love and got the response

    love has no meaning.

> The child tearfully reported this to Paul. The next day that error message was changed to

    I don’t know how  to love

> in which the extra space before "to" hints at the command needed to solve the problem.

As well as the _Internationalization_ section of the UCB Logo PDF manual Page 99
https://github.com/jrincayc/ucblogo-code/releases/download/version_6.2/ucblogo.pdf
> The two spaces before `to` in `I don’t know how\ \ to` aren’t a mistake either.

**Comment by brianharvey** [comment]
Indeed, this is deliberate.

**Comment by brianharvey** [comment]
Indeed, this is deliberate.

**Comment by jrincayc** [comment]
> > A story Paul Goldenberg recounts from the early days of Logo is that one day a child typed the command love and got the response
> 
> ```
> love has no meaning.
> ```
> 
> > The child tearfully reported this to Paul. The next day that error message was changed to
> 
> ```
> I don’t know how  to love
> ```

Thank you for that interesting bit of history.

**Pull request closed without merging**
