### PR TITLE
Release 6.1 Miscellaneous fixes

### PR DESCRIPTION
**Pull request by jrincayc**
This updates the version to 6.1, and makes multiple changes.
* Updates version to 6.1
* Adds more automatically generated files to .gitignore
* Removes README and copyedits README.md
* Removes automatically generated html documents from repository (Note that automatically generated PDF was left since otherwise tex is required to create it.)
* Switched to using texi2pdf for usermanual since it allows interdocument links and fixes index file generation.
* Added ucblogo.iss to use with Inno to generate a windows setup program.
* Switched version getting from svn to git.
* Updated windows build file.

### CODE REVIEW

**Comment by jrincayc** [comment]
@brianharvey  Here are my final changes for 6.1

**Comment by brianharvey** [comment]
Great, am I supposed to pull it?  It's your repo, right?

**Comment by jrincayc** [comment]
> Great, am I supposed to pull it? It's your repo, right?
If you want to review it and pull it you can.  
Otherwise I'll review it and pull it in the morning (unless I see something else I need to fix.)

**Comment by brianharvey** [comment]
I'll leave it to you.  Thanks!

**Pull request merged**
