### PR TITLE
Release 6 2 work

### PR DESCRIPTION
**Pull request by jrincayc**
Various work on creating the 6.2 release.

### CODE REVIEW

**Comment by jrincayc** [comment]
@dmalec @brianharvey FYI: I think I am about done with the release, I plan on releasing it on Wednesday or Thursday.

**Comment by brianharvey** [comment]
Awesome!  I can't thank you guys enough for rescuing ucblogo from my neglect.

**Comment by dmalec** [comment]
That's great news! I'm happy to be part of the 6.2 release :)

**Review by jrincayc — COMMENTED** [review]
I have re-reviewed the changes and I approve.

**Comment by jrincayc** [comment]
It is released.

**Comment by dmalec** [comment]
Awesome! Thanks for putting together the new release! :)

**Comment by brianharvey** [comment]
Thanks again to all of you!  You're terrific.  I've updated my web site to point to this release.

**Pull request merged**
