### PR TITLE
ISSUE-36: Handle command line arguments across environments.

### PR DESCRIPTION
**Pull request by dmalec**
This code change attempts to address the bug portion of issue #36 "Cannot run logo scripts from command line". It does the following in wxWidget builds:
* Pass wxWidget `argc`/`argv` into Logo for evaluation.
* Capture `cwd` before it is changed to the *Documents* directory.
* Use the captured `cwd` when loading files passed as command line arguments.

Test Environments
=
* OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
* OSX Catalina 10.15.7 console only (*tweaked configure.ac to permit*)
* Ubuntu Bionic (18.04.3) w/ wxWidgets 3.0.5
* Ubuntu Bionic (18.04.3) console only (*tweaked configure.ac to permit*)
* Windows 10 Home (1903) w/ wxWidgets 3.0.5

Tests Run
=
* Running without any command line arguments maintains current behavior.
* `<logo_executable> - hello world` sets `command.line` to `[hello world]`.
* Passing in a relative file path runs the code.
* Passing in an absolute file path runs the code.
* From the `tests` directory, `<logo_executable> UnitTests.lg` loads the file and symbols.
* OSX and Linux can run code via shebang script.
* Windows can run code via file associations.

Caveats
=
* Does not address the enhancement request for wxWidgets builds to be able to run in console mode.
* Does add to the future i18n work.

Risks
=
No observed negative side effects; but, these are changes with a potentially larger impact:
* Made `exit(0);` conditional in`main.c` in order to run cleanup code in `wxTerminal.cpp` after the execution loop is done.
* Removed check that limited file argument processing to only executables ending in `logo`.

### CODE REVIEW

**Comment by jrincayc** [comment]
Thanks, I'll look at it later this week.

**Review by jrincayc — APPROVED** [review]
I have reviewed the changes and tested them on Linux. I approve.

**Comment by jrincayc** [comment]
Thanks for the fix.

**Comment by dmalec** [comment]
You're welcome, no worries! Thanks for the work you're doing on keeping UCBLogo current :)

**Pull request merged**
