### PR TITLE
Adding wxCommandHistory

### PR DESCRIPTION
**Pull request by jrincayc**
Adds wxCommandHistory to windows makefile.

### CODE REVIEW

**Review by dmalec — APPROVED** [review]
Reviewed changes, verified on GitHub Windows build VM, and approve.

**Comment by dmalec** [comment]
Did a bit of investigating on why my local Windows testing of the code change didn't run into this during the build. I've realized I never updated my local setup from my original (and incorrect) understanding of the Windows build process, so it doesn't use the `makefile.msys` file. I'm afraid I have egg on my face on that - I should have updated it as I learned more about the build process. I'm going to rework my local Windows build env so it is not a special case and instead uses the proper process.

Thank you for fixing this :)

**Comment by jrincayc** [comment]
> Did a bit of investigating on why my local Windows testing of the code change didn't run into this during the build. I've realized I never updated my local setup from my original (and incorrect) understanding of the Windows build process, so it doesn't use the `makefile.msys` file. I'm afraid I have egg on my face on that - I should have updated it as I learned more about the build process. I'm going to rework my local Windows build env so it is not a special case and instead uses the proper process.
> 
> Thank you for fixing this :)

You are welcome (and I missed it during the review as well).

I am mildly curious how you managed to build in windows without makefile.msys?

**Comment by dmalec** [comment]
This is kind of interesting... I remember doing some set of things in order to use the standard makefile; but, it was all in terms of tweaking the environment in various ways (I'm now wishing I'd kept notes).

I'm glad you asked :) - I haven't started tearing down yet and now I'm also curious to see what I did. I'll try and figure it out and follow up.

**Comment by dmalec** [comment]
I still haven't entirely figured out what I did; but, I think I have produced a reasonably close version of it and capture it here:
https://github.com/jrincayc/ucblogo-code/discussions/109

I'm _really_ wishing I'd kept notes at the time :)

**Pull request merged**
