### PR TITLE
ISSUE-69: Add a LINEP predicate.

### LINKED ISSUE #69: There should be a line-input version of KEYP
KEYP is defined to turn off echo and go into character-at-a-time input mode.  That's the right thing for the single-character-command sorts of user interfaces I was writing in Logo at the time, but today I want to be in line mode (so the user gets Unixy line editing ability) and still find out if there's a line ready to read.  So either it should have an optional input
(KEYP "LINE) or there should be a new LINEP predicate.

### PR DESCRIPTION
**Pull request by dmalec**
Resolves #69 

Summary
=
The intended implementation is the following:

Given a new predicate `LINEP`/`LINE?` is added
When code invokes this predicate
Then it will tell the `wxTerminal` to use `LogoLineInputMode` (_explained below_)
And it will inspect the active section of the `wxMain` buffer containing the data feed for `getc` (AKA `getFromWX`/`getFromWX_2`)
If it finds a `\n`, then it will return `TRUE`
If it does not find a `\n`, then it will return `FALSE`

Given a new input mode `LogoLineInputMode` is added
When the `wxTerminal` is in this mode
Then it will accept input as if in normal mode and reading instructions
Except it will not save input lines to the command history

Test Cases
=
Input lines are accepted while the turtle continues to move:
```
TO looper
  LOCALMAKE "ch "

  PENUP
  WHILE [NOT EQUALP "X :ch] [
    IF [LINEP] [
      MAKE "ch READWORD
      LABEL :ch
    ]
    FD 2 RT 1
  ]
  PENDOWN
END
```

Input chars are accepted while the turtle continues to move works as before this change:
```
TO looper
  LOCALMAKE "ch "

  PENUP
  WHILE [NOT EQUALP "X :ch] [
    IF [KEYP] [
      MAKE "ch READCHAR
      LABEL :ch
    ]
    FD 2 RT 1
  ]
  PENDOWN
END
```

When reading from a file, `LINEP` worked intuitively (at least, from my perspective... mileage may vary 😄 )

Test Environments
=
OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
Raspbian 10.6 (buster) w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/o wxWidgets - displays expected error message that LINEP is unavailable
Windows 10 Home (1909) w/ wxWidgets 3.0.5

### CODE REVIEW

**Comment by jrincayc** [comment]
@brianharvey Any thoughts on this? (I'm kind of waiting on you and dmalec to have a version you all like.)

**Comment by brianharvey** [comment]
Sorry, yes, that looks terrific.  Thanks @dmalec!

**Comment by dmalec** [comment]
@jrincayc & @brianharvey - thanks and sounds good! I'll take the following path:
* In the case that `LINEP` is called without wxWidgets, display an error message akin to running `KEYP` without `FIONREAD`.
* Update the PR accordingly.
* Remove the DRAFT label.

**Comment by jrincayc** [comment]
Thanks for the fix.  

P.S. I plan on a making a new release later in December.

**Comment by dmalec** [comment]
You're welcome, no worries :)

Awesome, that would be very cool!

**Pull request merged**
